# Generated by Django 3.2 on 2021-04-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'Country Population Data'},
        ),
    ]
